sudo: required

language: node_js

node_js:
- '7.8'

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_f0ebdbae76d9_key -iv $encrypted_f0ebdbae76d9_iv -in id_rsa.enc -out .travis/id_rsa -d

install:
- npm install
- npm run dist

before_script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id_rsa
- ssh-add .travis/id_rsa

script:
- export DOCKER_REPO=potic/potic-client-webui
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr '/' '-' ; fi`
- docker build -t $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER .
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG
- docker push $DOCKER_REPO
- if [ "$TRAVIS_BRANCH" == "master" ]; then ssh -o "StrictHostKeyChecking no" "$DEPLOY_USER"@"$DEPLOY_HOST" 'bash -s' < scripts/deploy; fi

env:
  global:
  - secure: G8paawqzotm0HE+nb1vRumeomqhHX/XmgQMHCNI9DuoPl6AqMwVq6tViLM2hVHcqlGIj1cNA++Ju1eILmSGeKaZE6NQW4YQf0KVyZOrNXb4ZGFNfsV6+PyaudK46a1//WXlFFDwQVPxyfBz2A+2/3QYJpoKz4ZTIbx8im7cp53uv4uNeTsVao52+tG5sUZ2bcBzVPPLj5/47bZkjuAOwa/9c0yH35GD5fczc3omlxVA5e7FfnEDFuIgH/hboYlsn2Tn5HudStPbtC/6kaqx9Lh1YaVVlhV0PfKXKJams83E0lA0mtn5c9qUKtJSGOa6j7XiQtoheBGEDM2UA38UhSDa49n99O1LkAnT2WjlR8TMZd4az6EiGE3jOPq5nWTDrEav0A+Naw2P3aj29GXvpg2w5NHNKWZxKdqZGgKAaEpMeLqenIbsLki1KTmNReTPat3smdT6xqlfzGasyUcJFslxbIoCdUlN5znyT4MNDg1HwIJFGIMkPQlYV9jfJF0f+vkVMUGTZW3F8vufwOMylWPf6JAq/8iNyD0GLiuRNoGcHVQuwRgWC/mu40sTY+n432+U0g3sa0q5d1fhCx88odcw3RW2NmuG2FSxylQkYWC7i4azgQE0i1Ev75UaI0jzvLNT2cf78gY4ZYRPUbJbixI/D9982DhjktJVXkvOD+sg=
  - secure: iQq2dc1lgljl7P7gcrZRwPEOPRk57phmc7cm+sgexctyh4Gk22HkjzQkAzT7zV0yRO0CnprmxBtdJYEtsc18wfbnA3FG1zR2M4v1ogRCushJHJJSB3ktHQ7BQB6mFoWgyJ1kZG9wtvCCfkGj706Yl5flDl66icYMacGWHvm+cR8+2UimVwbPWtqp28ZTxLWM1UTamP+1+7jMmxvGRYqeNJKJrPqFf9bfF6bGDPxqTq048ShVzI8FgX0LP46dGBfzHK+vuazKFYB2f7GtO1wyOm2gdjDJtUVS0rpi4wWIy/bACc0c/K5tbJN/hYr92YCnoSYj9redRgTWFbxT1E1GGRGuwO8ar7LeDlNebLIEyayxZ74z+T99zqeOjjQ4FPWYBSvzfbVLznEytghV2zfvjTjUHV6q3MigUB1Kh+LJfGyTS/FNZHtj/w1ZAETV08wQEKqmAs6A/BJh9AFG4r+GUtY2tW7P8jUnGxnK9QS/wdJ4fttHwITN932BBqUQM8jkEd+HrRuk/PQrlBBmNolUgNWzTbpm0Q43NDHMqeTT8H9rKYPxt63epqLiUKTluFHKivkeH5UYQUMhEH3vlC8e1k12IdaOw/oO8Ij1owupsNHgi3/as9btfAyQX8hzAX+YyNsfWVAzxsz9pihXqEEBrCh4iP226s6e1wXyZ1i138w=
  - secure: DSQWuFHVkbUW+dFEueIMxN7khKjjL8kQmXiChXjjJUUAkdXoJCqN7Mp4IvujLzppNpmgFHdvfSW1OdfIQSa8iJR8LeiWqPyWbnio//q+PR3i2EOhESNXh5ATpj8SoiMgMPfz6zS+eDTvZ1ks7A3xOen8ElMt1hmeh6ZetiFgrcm4RX5NWybFINi+n2JxmEf55VHaofNpLYayLfoT/sbMyj1uxSKwCuX/rMZ8355c9LhKP/CSNwXfLTIiqhiWSOK0ZZMUEP/TNQz393ALtdoOCNZ9imSKpJN7ZC+bLaPWImzi7uDuhhQLqQ5pcH0XKZjnONuG2nJL7zc7NdLxHOVcU8nRqnvj254kJmUrmoOwA6ShbeDOS7ljL5mYznTY2bTxq6e5y3p4XIG5sQWuhgOk67HFO1fnLlVG4QQ/OcSdm3rqrZfzVpTJFqxRPd16Nc3WIIUECXJnwka64XVrC1cbeHGk/iTNa8aCxaUsox7JsbspclRHosnhwu5b7boIpnfO0BE8fAf+wqWMORwyQrnf9daeUVWCA8jYqdx6gvbEyG5Tu9mkWfZKWYhnc7X7XtH9/BCDnBWitv4miZf8u9qDAden118nBzDIbaMi/dK2HYrJ/evPpXai5C3a62CYWPRYW1hyTetevTxELSlp4uFtbpt0dlDtEeQrL+MS1eMyIak=
