sudo: required

language: node_js
node_js:
- '7.8'

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_f0ebdbae76d9_key -iv $encrypted_f0ebdbae76d9_iv -in id_rsa.enc -out .travis/id_rsa -d

install:
- npm install
- npm run dist

before_script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id_rsa
- ssh-add .travis/id_rsa

script:
- export DOCKER_REPO=potic/potic-client-webui
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr '/' '-' ; fi`
- docker build -t $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER .
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG
- docker push $DOCKER_REPO
- if [ "$TRAVIS_BRANCH" == "master" ]; then ssh -o "StrictHostKeyChecking no" "$DEPLOY_USER"@"$DEPLOY_HOST" 'bash -s' < scripts/deploy; fi

env:
  global:
  - secure: RSvOcph3h3Iy4RJ8PBK3d3axOwB0QzO7rr31F39PxmzrhF0JVdVl5yZhHLsx2YtwKH3ky1yL4U+QQhVMybNM7Ynf3A/Dk7IKjG1OCSdpJk9d3iuUvuinRhv4ra63BTkLnD964P3LwLWeK3r5JmNQ4SzkdGQopzdjOJC02TV/R//jcOsCwW/b2z6SJUFycvZi/YtWVJr7XfFTXjRIAb9g5s7G1dOqsM8aHVYJ4cdlRIkiiO+kCDTfB8rchmTKw9kX6ohEwbJlF4yJv47g/bRPcaBuCthTXm0M0mFP0pKblylq4u+csE6i3wd4A+H7HPiH9PS+QFN+mkVMY5kejpcVH+62vcJJu3hOCSF+uaPGoSY9kf0DemsqfwusS9pkDsmZneLqdFlu1GM10J5yFIdJDI00Shn76YjhkbnaMTTUOQbiv7jqeTAaAtY+i5wI2XQbSREGB4KgV82gYWQKB1fsi8JrHTCX5KoE34uSHuu5tQm/fQhW6b2UY1FgbgSW1RihEoxCmbfxX6L19pKmLLtftSDvGWrRr5W9ZzRO+d+KJjjWH3ANohQLO4gbafo2X+CdEjAW0Z8I1BkoF0D5WqQWM5mDeLrx4z9deDbGRhYOYVRtoXB27NKi6FUCPxrtQ7Ft9ScikSrMSvum+rC4ajgMUkrleUajDDtkgl/aZRe0xGo=
  - secure: AcD5f1vAaTq7aBjAhGjwSclc+iZjQZzn4rf5pXN5ZiWGkVvLfC9BfZj2Ln4G2NOLOynk9nHULEBYmZdcbGskTRUlxGCiOpuy9eUMWxS1ALj2tPPizlI9Sni4WpK0A3W0Mq54axH00G2q8cx1Wcrd/jrzCk17sFuIe8sXulLufXETlsN+OfF1vW1uYJ8mwQAE6k0t15s1o/yldvQNSlfaWC3rv/Jk9p08I1s9l4vbRczPYtAm82R7TQLpvX2YEzzbjUQ+EwapF+6DhkNvqK/9Ym2+k8O6oRJJtiC3qwJuItEPpWKd5EKnIsc5mxIVEBgPjNfx8jz5qK1aM2AZelNkMpiis9DH/jjuvg/Ef2nKo6WpLr68vw4oijDcqb7K/X6Y8tJuNPbDxMGE51/z5SYJhHjt5iK9b+yfgs8QMyloic2S0OsBgkqLI+NTdfzv7V4FMgPo64J4UVVnYVNx7bTPzJfmc5ar7wxSjV16kuZyFt+M1MgNBMGUFcOHihrNeuD0WO2aX9k5VLj7X/HN6PipKjDhf8aKjq8F2F8aD1VOZp/ZxuMFvBS+otNXvzPeUmztWMUF8yyM2q8aRNwL3d943hNTftc6PwVSqRuejrI821afopoVawHssjTRije073mCF99JERig/gMZ8Iy7HIZCfgOYuCgMUGHov9Gqvey8zFo=
  - secure: uvFEPLR5WZMwSuy19+Ep/9CCti176YfBxY4YgNrtf2Q6fIMOUk3aJ2b54fcH0N3ZM17ChempVeuoX24klpHraMTy3zTkcc0MKt5T6VUAKH0a3U8ZOYd/zH2hc19d5E8bvPrO0isPgJhhuQAIzHVJM+zEJyHviHotFnh+ypFwm8mJgLG6X8lalZXgAOJh1IjI3kpGJHkKHlwCqezz64+CDZojfpZF+I/LtUx1DsNFHghkOy4Hc3K6owlZrQJfaqUNIGhsc1mKpUj9qWPRWtIxVmlyIw7on55qEFj/Ong2p3+FbxhJGQE75xkRRIufCMhJISaGHsQjYUa7sIJd9dlRRWuD8vxQis6+bwKny85KomA1kS4urg8i1wHwDM+uxYjXBMVxjbxn0jpBZFbfJisT49FzMUh9sU7o7aOtd4SAOtZPTpw6RdZU7T9amd2cNNktNm4Om4u42RVWyQ6nczonUAf9xdp4D5sxM+ec72HbCOmAzVA3DfkBCJQtNEXVu2pKHdgAvIBh9ujfWkOf1JxTYHmPHm1zbhEFroJap4A/Vc1WDBDIFsTHSVvnJSX5gsBIFw93kNLfu7ceNHaQV1evnonx3UXbOgNNEscPwox1Oq70L2L4yupH1HtJCNociLktRt1v2bMiYPaxy47p4Oj4keyH+xTE1NgDjkxa1nnZhnk=
