sudo: required

language: node_js
node_js:
  - "7.8"

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_cc6f55bd256b_key -iv $encrypted_cc6f55bd256b_iv -in id_rsa.enc -out .travis/id_rsa -d

install:
- npm install
- npm run dist

before_script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id_rsa
- ssh-add .travis/id_rsa

script:
- export DOCKER_REPO=potic/potic-client-webui
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  | tr '/' '-' ; fi`
- docker build -t $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER .
- docker tag $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$TAG
- docker push $DOCKER_REPO
- if [ "$TRAVIS_BRANCH" == "master" ]; then ssh -o "StrictHostKeyChecking no" "$DEPLOY_USER"@"$DEPLOY_HOST" 'bash -s' < scripts/deploy; fi

env:
  global:
  - secure: Q/C8AqtwUvn2gAFsSHUuCHtiesBPe6mPqDbZJog75HKN0QvENUiqfFrvEPq7ylhbSZh6Z+lUd+H2DvzAuBmAfh40ZTRNzGDxvAZqYaRHcILJh8mqVLoilnmM6DPwuU3k+JKmLWFHiVlMGuUG5lI0OMEGMs6rasKLuSDG8QmQB/1I4g2zZI8212ww54c7RSE2+zZ2nQPTt1NLsazSnkUQZEqRWge8mryjDHRf6CZGLOIrwOk12Rr+1yKXPO7QM7Pk4SaV7uuIQr47XthaZn1X/Jb17jkqWsRH7f+rxLUvZtUSZAs50jw9pB6ZmzjOixKwZiV6moFYPoMpib8uc3ietaE+RMcQkbMgh0YdhJtocJA93i+8Ge6Q7IxUbwYEoO6ttKFuh06iBcRN0KddK7/UsXIsWlijNempxFn8+6tcxyiq6/t1zs/S3hgpeWBZg9hzikLhWrr7QE6glyGWQR9d1KZ2TL44qigH7aidpnt+c9TYgUhCGa5wD8zJ1gky1741itrWw5xrNxE3aj309SsFzHHqW+9/Jw2vBEV530OP+4QRTReHBqgWj51H2K83MZa6wskwQZjNzKm/BfiClXTWM/TyGSkfprhfP6a8xqGNQVbvIOvF0za3AxAjshtuaAmJNFV3QfnK7KDVAr4BRGK6g5PrjsRYwBpp48i/SC7xHV8=
  - secure: eSIF9pBEH+Ai9vnHAbK5Omgd6A/OaJfRjtz4CsugbSSbXC7KIw5BkxTeBD9MphQXxUICDnrbAI+u7vdgog5gkZtj5QSdo53tGpsfyj3NkCFHs9I+UQwukDiJiDGUzrTUxv9B3vJGdHBdOCN0ZRlDv4nOLa5ZSgcre/XbRj+sXU6DyDz6U/vV6IsNp81aR7Q6KXxHv4JIaVUcZLFyow05xCevDCztI1w4Ce8ucTagvZ+HiQev78RZlkZOoUangBYKJpaxLNbEt5fu9FJmqAZ/qSI2cjNogdU7LcDL+gSoAmYLl2sEXJFy66T9YJM62/Hxb57MCaKf+vk41D0Javz+sVSLp8G+M1UhcT7IDs6n7sJn//aYvyf8cvPKonlb2vUdhwENFvqKRN4BJg1Yoi+N64RXNhsNuBaHjN44Njj/VvFgf1qrHLw6jFAN0YowCEMTO5NGLuAyeVz8901WqIjmSbwhm+juA3mCp2aqwThzvAEUBA/vCbWzbCQqYar1/oQI6YyIxynZnXMSvcpMmllc0NGgrnKiC8GGhZP6FArxix16hkNXJ3tziLmjbLK9/AbmrZPfBrHlXmR7JjFpcVJGuGCzNVnlmHuuAy0ckI16Ufs6AInu2TkcSmpsURd8mAovHgy34qmHWwFarJUGJZTR+ZgbkTSMAH9+PR9aLOHkMjg=
  - secure: ST28zaUKMWADmByaswXSofTAinUsEqWy0dGwEPr6ELY3t9qtlcdAa10fOwokR8nAYBaxZoCb+z9qk6PLqhLCwXRccJWgXUblxloN6Y9znp9Kmc5v+q4T7mCzP5qNs+Z7FhKZAjtGE7upEVOB1pnO1wtaACMBTzeVgWXMvVVzI59y11TxWwkxc9zgP/QAW5OA/XPTI8GYumAZsSels/gbYvyTq+FfPErQlZw2EQsGi2kbzLeoJXqgwVMly/XoYdS3SupbB4YPjC08mAqcfKbE3EuKIrwiem7fKuVbQMyCEXYLSFSYmOYC968+PmHWMDxsDMQcCbaamsJwO/3kS/8wl2VrOkmmAZadbCwqUI9AriXbmMQtW5jvtFRf/s9Y2itDxLUMSWxKiQvEJ42SK40PY5viviVh84FWmzupFjqNJhThPvMLx2Gl3o1Ii05JuzMIJyj+Ewjd8IbtAbZySK0nDCV5gH+A79YD/Ge7OZMiguct79Pbqz//9EwOHuFo8ATzzYM6tVSOeTRTMKxvCp2Hb59gTbcb3gXSRdQHlJL+J2IPCu4tpw0yAW58+MLvSfFAcW8C9AAUjkxKwWTyLFO43ffY0hErfzypXM2VKQv+6IbXqRoao1fOGXVl0nRLTQ5M2P3d5JIT7L9jELuFEfjui0Lj9SiGVQLdo75EmjEDGZs=
  - secure: j6X0rnwG8WnjdQgBEBs1X1GLgxME4F+zcSr3MYwLTju5GkLW2gtFyOrEnW6x/rHOeQIPuEJLrf9z4ctG+5E41QsHJiEDu/IQxeDGVUvgIEcFAMrpUHob2xlZKeXFdT8d6sjtPE2705Qr6A9sXBp/8GpIilsEcATjLRH8T1rBcGWkQnSfu16JDtEgPzmEdLzOL6KfFmYyoR5qxtVwBceW/V37AUfqVAcHOXlHaX2KhvMx5gLL3Jp7ZTs2SISbRYdQIRkmjID7R7OQRmD8G697r4pqPZglqlPs+NMuFPSNMOH4saXxshxMOxWu7Mqmi19XeSsdeWM7MGfbKns3vcUUnubi8LMmIhjEUXsZ0HcdWBkBebQxbjNPo8rMCNDTGytOvU0/9NXuKWYbZMePBayPSEd8tqFvL5WMs0LRIaw39Km8zd1neAlJvW6PnlaGw5U2AOg4JKBsvHx5wfv+dhNQYeOdbJ7CmZPRPiSaUeDlA0M//GvZ1ygaseymgfSXjH1hp08NREJiElB6S/1DtybJZeFi4TAOSmeap/mkWB87RuDYmDGloNfVZHFKnfmaGscC69tk/zdm6L8Hs1BRGREm0eMcWe3KVo446r+4kmd6ZTI0EiwqklyMZb832vPVniaJx193yk7RkuMlsZ93VZwI9LDKiELjB6agTTmLGZBVhFo=
  - secure: M/fHfj1DDmIVPhbL7ijNi1AmVWNnk/joyj5j4XfDuR9jBNLG5a2OSvEB7BRxf+In7R9C1bCJqe3tCF8H6LQiQAFTCpY/Rrqu71yTs/8Jzvv0z42126jfbrTWTFt+PRo9fAYZVWGcGv6D2LNmfTITW2QvzRSeDpB3fv/yWGWYB0V9XABG+7MXN1459gG2HYyJDw6NStuTI8tnpbfpXX4k6QXvBXG2C8m+r6VYNrhX2sYQtwEM35ypy0Otk/5Q4pAr2D48Ori1rJtM5v84IxVkcXwCJEETmuPQLOXjtPVosTERaaK56dhfmDVtCQccdXPwF3tQnJgBHM9tk0jgYNNkWpHiA9Sjx0hfySIRIQVKF730LdYsIwh3oUJh3fKoBqIDDKkNHsDwqJV+FErQQam6+/0TSaVmezQtnvUk5qucZc6BKNaaGdQqX7h4Rmygw4C5fr4MbiM3wzTvVSe4qro9tGq7w+DVkMYZHLNzklNeN4q/7K2mq7LBpai/uBrCbzCXrBYEu6/qYYCa2NrNtmBEm2bwoiGzLfatLq1nCkNOAkshFCpYvpD95SI6gh6oRZZbjnEKveGI1kP/vT9PbnAXWnY36tX1STt2VhXM0/BzwCkaT+6zs8HqDnKn0wNRaaifDdFjUzb01JA8cvDOlVX5nvj0V0mDOBimljSWuT8R278=
