#!/usr/bin/env sh

##############################################################################
##
##  Stop and kill currently running docker image, pull newest version and
##  run it.
##
##############################################################################

warn ( ) {
    echo "$*"
}

warn "Currently running docker images"
docker ps -a

warn "Killing currently running docker image..."
docker kill potic-client-webui; docker rm potic-client-webui

warn "Pulling latest docker image..."
docker pull potic/potic-client-webui:"$TAG_TO_DEPLOY"

warn "Starting docker image..."
docker run -dit --name potic-client-webui -p 80:8000 potic/potic-client-webui:"$TAG_TO_DEPLOY"

warn "Currently running docker images"
docker ps -a
